name: Deploy Docker image on EC2

on:
  workflow_run:
    workflows:
      - Build and Push to ECR
    types:
      - completed


jobs:
  build:
    name: Pull Docker Image And Deploy on EC2
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with: 
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            ${{ secrets.EC2_DEPLOY_SCRIPT }}
